### ISSUE TITLE
Allow unit tests to run in parallel 

### ISSUE THREAD

**Issue by albertogviana** [tabakuj/fileservice#2]
Could you please amend this code: 

- https://github.com/tabakuj/fileservice/blob/main/internal/adapter/repository/db_test.go

to allow tests cases (and subcases) to run in parallel and enable the race flag. Add all instructions to make all sub cases being executed.

As well as writing one test for the https://github.com/tabakuj/fileservice/blob/main/internal/core/services/service_test.go

**Comment by tabakuj** [comment]
Hey @albertogviana  i updated the requested changes. pls take a look when you have a chance and let me know if there are any more changes that you think i need to make.
